version: "3.5"
services:
  db:
    image: postgres
    container_name: postgres_container
    build: . ### cuando quiero definir la ruta del dockerfile
    # env_file: .env-local
    labels:
      author: "SebaZuniga"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_DB=database
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql/data/pgdata=/var/lib/postgresql/data/pgdata
      # - "./data:/data:rw"
    ports:
      - "9001:5432"
    networks:
      docker-network:
        ipv4_address: "172.0.0.23"
        # ipv6_address: 2001:3984:3989::10
    restart: unless-stopped
  web:
    image: python:alpine3.7
    container_name: python_container
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    labels:
      author: "SebaZuniga"
    volumes:
      - .:/app
    ports:
      - "5001:5000"
    networks:
      docker-network:
        ipv4_address: "172.0.0.24"
    depends_on:
      - db

networks:
  docker-network:
    ipam:
      driver: default
      config:
        - subnet: "172.0.0.0/24"
        # - subnet: "2001:3984:3989::/64"
volumes:
  postgres:
### para correr el archivo se usa docker-compose up || docker-compose up -d ###
